package com.dms.rga.asthma;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AsthmaSeverity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Oral Steroid Risk")
	private java.lang.String oralSteroidRisk;
	@org.kie.api.definition.type.Label("Supplemental Oxygen")
	private Boolean supplementalOxygen;
	@org.kie.api.definition.type.Label("Status Asthmaticus")
	private Boolean statusAsthmaticus;
	@org.kie.api.definition.type.Label("Hospitalizd")
	private Boolean hospitalizd;
	@org.kie.api.definition.type.Label("Attack Severity")
	private java.lang.String attackSeverity;

	@org.kie.api.definition.type.Label("TOW")
	private Boolean tow;

	@org.kie.api.definition.type.Label("Asthma Severity")
	private java.lang.String asthmaSeverity;

	@org.kie.api.definition.type.Label("Risk Score")
	private java.lang.Integer riskScore;

	public AsthmaSeverity() {
	}

	public java.lang.String getOralSteroidRisk() {
		return this.oralSteroidRisk;
	}

	public void setOralSteroidRisk(java.lang.String oralSteroidRisk) {
		this.oralSteroidRisk = oralSteroidRisk;
	}

	public java.lang.String getAttackSeverity() {
		return this.attackSeverity;
	}

	public void setAttackSeverity(java.lang.String attackSeverity) {
		this.attackSeverity = attackSeverity;
	}

	public java.lang.Boolean getTow() {
		return this.tow;
	}

	public void setTow(java.lang.Boolean tow) {
		this.tow = tow;
	}

	public java.lang.Boolean getSupplementalOxygen() {
		return this.supplementalOxygen;
	}

	public void setSupplementalOxygen(java.lang.Boolean supplementalOxygen) {
		this.supplementalOxygen = supplementalOxygen;
	}

	public java.lang.Boolean getStatusAsthmaticus() {
		return this.statusAsthmaticus;
	}

	public void setStatusAsthmaticus(java.lang.Boolean statusAsthmaticus) {
		this.statusAsthmaticus = statusAsthmaticus;
	}

	public java.lang.Boolean getHospitalizd() {
		return this.hospitalizd;
	}

	public void setHospitalizd(java.lang.Boolean hospitalizd) {
		this.hospitalizd = hospitalizd;
	}

	public java.lang.String getAsthmaSeverity() {
		return this.asthmaSeverity;
	}

	public void setAsthmaSeverity(java.lang.String asthmaSeverity) {
		this.asthmaSeverity = asthmaSeverity;
	}

	public java.lang.Integer getRiskScore() {
		return this.riskScore;
	}

	public void setRiskScore(java.lang.Integer riskScore) {
		this.riskScore = riskScore;
	}

	public AsthmaSeverity(java.lang.String oralSteroidRisk,
			java.lang.Boolean supplementalOxygen,
			java.lang.Boolean statusAsthmaticus, java.lang.Boolean hospitalizd,
			java.lang.String attackSeverity, java.lang.Boolean tow,
			java.lang.String asthmaSeverity, java.lang.Integer riskScore) {
		this.oralSteroidRisk = oralSteroidRisk;
		this.supplementalOxygen = supplementalOxygen;
		this.statusAsthmaticus = statusAsthmaticus;
		this.hospitalizd = hospitalizd;
		this.attackSeverity = attackSeverity;
		this.tow = tow;
		this.asthmaSeverity = asthmaSeverity;
		this.riskScore = riskScore;
	}

}